### PR TITLE
Update client name in prober

### PR DESCRIPTION
**Pull request by BinChang**
Use "options.clientName" as part of the prober title, so prober statsd of different clients do not collide with each other.

### CODE REVIEW

**Comment by Raynos** [comment]
noice. lgtm.

**Comment by Raynos** [comment]
Suggested change: major version

**Comment by Raynos** [comment]
Also make a new major upstream in sirvice as well. And add to the sirvice MIGRATION.md document

**Comment by BinChang** [comment]
I agree with you. This update might break some dashboards.  I am changing the version.

**Pull request merged**
